# Generated by Django 4.1.1 on 2022-10-02 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "description",
                    models.CharField(
                        choices=[
                            ("LOAN_CREATE", "Zastava"),
                            ("LOAN_EXTEND", "Prodlouzeni"),
                            ("LOAN_EXTEND_AFTER_MATURITY", "Prodlouzeni po splatnosti"),
                            ("LOAN_RETURN", "Vyber"),
                            ("OFFER_CREATE", "Vykup"),
                            ("OFFER_SELL", "Prodej"),
                            ("LOAN_TO_OFFER", "Presunuti do bazaru"),
                            ("LOGIN", "Prihlaseni"),
                            ("LOGOUT", "Odhlaseni"),
                        ],
                        max_length=255,
                    ),
                ),
                ("price", models.IntegerField()),
                ("amount", models.IntegerField()),
                (
                    "product",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="product.product"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
