# Generated by Django 4.1.1 on 2022-10-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statistic",
            name="profit",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
