# Generated by Django 4.1.1 on 2022-10-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statistic",
            name="description",
            field=models.CharField(
                choices=[
                    ("LOAN_CREATE", "Zastava"),
                    ("LOAN_EXTEND", "Prodlouzeni"),
                    ("LOAN_EXTEND_AFTER_MATURITY", "Prodlouzeni po splatnosti"),
                    ("LOAN_RETURN", "Vyber"),
                    ("OFFER_CREATE", "Vykup"),
                    ("OFFER_SELL", "Prodej"),
                    ("LOAN_TO_OFFER", "Presunuti do bazaru"),
                    ("UPDATE", "Update"),
                    ("LOGIN", "Prihlaseni"),
                    ("LOGOUT", "Odhlaseni"),
                    ("RESET", "Reset profit"),
                ],
                max_length=255,
            ),
        ),
    ]
