version: '3.9'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    env_file: env/.env.backend
    depends_on:
      - db
    restart: on-failure

  db:
    container_name: db
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - env/.env.db

volumes:
  postgres_data:
