##### VENV
FROM python:3 as base

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt /app/

RUN set -ex && \
    pip install --upgrade pip && \
    pip install --no-cache-dir -r /app/requirements.txt
#    apt-get update && apt-get -y install cron # TODO:

ENV PORT 8000
EXPOSE 8000

WORKDIR /app/src

COPY src/ .

COPY src/ .
RUN chmod +x entrypoint.sh

WORKDIR /app
RUN chmod +x start.sh

ENTRYPOINT [ "/app/start.sh", "--loaddata", "--runserver"]





##### PEOTRY
#FROM python:3
#
######################################
#
#ENV PYTHONUNBUFFERED 1
#
#WORKDIR /app
#
#COPY poetry.lock pyproject.toml /app/
#
#RUN pip3 install poetry && \
#    poetry install --no-root
#
#ENV PORT 8000
#EXPOSE 8000
#
######################################
#
#WORKDIR /app/src
#
#COPY src/ .
#
#RUN chmod +x entrypoint.sh
#ENTRYPOINT [ "/app/src/entrypoint.sh", "dev"]
