FROM python:3.9

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PORT 8000
ENV EDITOR vim
EXPOSE 8000

WORKDIR /app
COPY requirements.txt start.sh /app/
RUN set -ex && \
    pip install --upgrade pip && \
    pip install --no-cache-dir -r /app/requirements.txt && \
    apt-get update --no-install-recommends &&  \
    apt-get -y install cron vim --no-install-recommends && \
    rm -rf /var/lib/apt/lists/* && \
    service cron start


COPY src/ /app/src
RUN chmod +x /app/start.sh # &&
#    echo "* * * * * root /bin/bash start.sh --update-product-status" >> /etc/crontab && \
#    echo "* * * * * /bin/bash start.sh --update-product-status" >> /etc/crontab && \
#    echo "* * * * * root /app/start.sh --update-product-status" >> /etc/crontab&&\
#    echo "* * * * * /app/start.sh --update-product-status" >> /etc/crontab &&\
#    echo "* * * * * root echo hello >> /app/cron.log" >> /etc/crontab &&\
#    echo "* * * * * echo hello >> /app/cron.log" >> /etc/crontab
#ENTRYPOINT ["/app/start.sh", "--cron-docker"]
CMD ["/app/start.sh", "--dev-docker"]
