version: '3.6'

# How to run Cron: https://stackoverflow.com/questions/69802579/how-to-make-django-crontab-execute-commands-in-docker-container:

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    env_file: env/.env.docker
    depends_on:
      - db

#  cron:
#    container_name: cron
#    build:
#      context: .
#      dockerfile: Dockerfile.dev
#    restart: unless-stopped
#    env_file: env/.env.docker
#    depends_on:
#      - db
#    entrypoint: ./start.sh --cron-docker

  db:
    container_name: db
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - env/.env.docker.db

volumes:
  postgres_data:
