FROM python:3.9

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PORT 8000
EXPOSE 8000

WORKDIR /app
COPY requirements.txt start.sh /app/
RUN set -ex && \
    pip install --upgrade pip && \
    pip install --no-cache-dir -r /app/requirements.txt
#    apt-get update && apt-get -y install cron # TODO:


COPY src/ /app/src
RUN chmod +x /app/src/entrypoint.sh && chmod +x /app/start.sh
ENTRYPOINT [ "/app/start.sh", "--loaddata", "--runserver"]
