##### VENV
FROM python:3.9

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt /app/

RUN set -ex && \
    pip install --upgrade pip && \
    pip install --no-cache-dir -r /app/requirements.txt

ENV PORT 8000
EXPOSE 8000

WORKDIR /app/src

#COPY src/ .
#
#RUN chmod +x entrypoint.sh
#ENTRYPOINT [ "/app/src/entrypoint.sh", "dev"]
