version: 2.1


executors:
  my-executor:
    docker:
      - image: zlapik/pawnshop-backend_backend


orbs:
  tools: signavio/tools-orb@0.9.0
  pre-commit: skoblenick/pre-commit@0.2.0


jobs:
  linting:
    machine: true
    steps:
      - checkout
#      - tools/install-pre-commit
      - run:
          name:
          command: |
            sudo pip3 install pre-commit
            pre-commit run --all-files

  deploy-dev:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and Deploy to Heroku
          command: |
            set -x
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a dev-pawnshop-backend web # this build it automatically
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a dev-pawnshop-backend web

  deploy-main:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and Deploy to Heroku
          command: |
            set -x
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a pawnshop-backend web # this build it automatically
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a pawnshop-backend web

workflows:
  push:
    jobs:
      - linting
      - deploy-dev:
          filters:
            branches:
              only:
                - dev
      - deploy-main:
          filters:
            branches:
              only:
                - main





#  lint:
#    machine: true
#    steps:
#      - checkout
#      - run:
#          name: Linting from .pre-commit-config.yaml
#          command: |
#            set -x
#            pip install --user pre-commit
#            pre-commit run --all-files
#
#  heroku: circleci/heroku@1.2.6 # Use the Heroku orb in your config
#  pre-commit: oandacorp/pre-commit@0.10.0
