version: 2.1


executors:
  my-executor:
    docker:
      - image: zlapik/pawnshop-backend_backend


orbs:
  tools: signavio/tools-orb@0.9.0
  pre-commit: skoblenick/pre-commit@0.2.0


jobs:
  lint:
    machine: true
    steps:
      - checkout
      - run:
          name:
          command: |
            sudo pip3 install pre-commit
            pre-commit run --all-files

  deploy-dev:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and Deploy to Heroku
          command: |
            set -x
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a dev-pawnshop-backend web --recursive # FIXME: Cron
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a dev-pawnshop-backend web

  deploy-main:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and Deploy to Heroku
          command: |
            set -x
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a pawnshop-backend web --recursive # FIXME: Cron
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a pawnshop-backend web

  run-tests:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            pytest
      - store_artifacts:
          path: test-reports/
          destination: python_app

workflows:
  push:
    jobs:
      - lint
      - run-tests:
          requires:
            - lint
      - deploy-dev:
          requires:
            - lint
            - run-tests
          filters:
            branches:
              only:
                - dev
      - deploy-main:
          requires:
            - lint
            - run-tests
          filters:
            branches:
              only:
                - main
