version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6 # Use the Heroku orb in your config

executors:
  my-executor:
    docker:
      - image: zlapik/pawnshop-backend_backend


jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: |
            set -x
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login 
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a pawnshop-backend web # this build it automatically
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a pawnshop-backend web

workflows:
  build-test-deploy:
    jobs:
      - deploy
