version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6 # Use the Heroku orb in your config

executors:
  my-executor:
    docker:
      - image: zlapik/pawnshop-backend_backend


jobs:
  build-test:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            docker-compose -f docker-compose.yml up --build -d
  build-deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            docker-compose -f docker-compose.yml up --build -d
            set -x
            sud curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container: login
            HEROKU_API_KEY=${HEROKU_API _KEY} heroku container:push -a pawnshop-backend web
            HEROKU_API_KEY=$(HEROKU_API_KEY} heroku container:release -a pawnshop-backend web

# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-test:
    jobs:
      - build-test
#  build-deploy:
#    jobs:
#      - build-deploy
#      - heroku/deploy-via-git:
#          branches:
#            only: dev # only run deploy-via-git job on main branch
