version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6 # Use the Heroku orb in your config

executors:
  my-executor:
    docker:
      - image: zlapik/pawnshop-backend_backend


jobs:
  deploy-main:
    machine: true
    steps:
      - checkout
      - run:
          name: Buidl and Deploy to Heroku
          command: |
            set -x
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login 
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a pawnshop-backend web # this build it automatically
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a pawnshop-backend web
  deploy-dev:
    machine: true
    steps:
      - checkout
      - run:
          name: Buidl and Deploy to Heroku
          command: |
            set -x
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login 
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a dev-pawnshop-backend web # this build it automatically
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a dev-pawnshop-backend web

workflows:
  deploy-dev:
    jobs:
      - deploy-dev:
          filters:
            branches:
              only:
                - dev
  deploy-main:
    jobs:
      - deploy-main:
          filters:
            branches:
              only:
                - main
