version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6 # Use the Heroku orb in your config
  pre-commit: skoblenick/pre-commit@0.2.0

executors:
  my-executor:
    docker:
      - image: zlapik/pawnshop-backend_backend


jobs:
  lint:
    machine: true
    steps:
      - checkout
      - pre-commit/all-files
  deploy-dev:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and Deploy to Heroku
          command: |
            set -x
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a dev-pawnshop-backend web # this build it automatically
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a dev-pawnshop-backend web

  deploy-main:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and Deploy to Heroku
          command: |
            set -x
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a pawnshop-backend web # this build it automatically
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a pawnshop-backend web

workflows:
  deploy:
    jobs:
      - lint
      - deploy-dev:
          filters:
            branches:
              only:
                - dev
      - deploy-main:
          filters:
            branches:
              only:
                - main





#  lint:
#    machine: true
#    steps:
#      - checkout
#      - run:
#          name: Linting from .pre-commit-config.yaml
#          command: |
#            set -x
#            pip install --user pre-commit
#            pre-commit run --all-files
#
