version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6 # Use the Heroku orb in your config

executors:
  my-executor:
    docker:
      - image: zlapik/pawnshop-backend_backend


jobs:
  build-test:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            docker build -t backend:v1 .
  build-deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            set -x
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container: login
            HEROKU_API_KEY=${HEROKU_API _KEY} heroku container:push -a pawnshop-backend web
            HEROKU_API_KEY=$(HEROKU_API_KEY} heroku container:release -a pawnshop-backend web

# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-test:
    jobs:
      - build-test
      - build-deploy
