version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6 # Use the Heroku orb in your config

executors:
  my-executor:
    docker:
      - image: zlapik/pawnshop-backend_backend


jobs:
  build-test:
    machine: true
    heroku container:push web
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            docker build -t backend:v1 .
            docker save -o backend_image.tar backend:v1

  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
#            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/pawnshop-backend.git dev
#            docker build -t backend:v1 .
            docker load -i backend_image.tar
            set -x
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login 
            HEROKU_API_KEY=${HEROKU_API _KEY} heroku container:push -a pawnshop-backend backend:v1
            HEROKU_API_KEY=$(HEROKU_API_KEY} heroku container:release -a pawnshop-backend backend:v1

workflows:
  build-test-deploy:
    jobs:
#      - build-test
      - deploy



