# Generated by Django 4.1.1 on 2022-10-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='interest_rate',
            new_name='interest_rate_or_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='date_create',
            field=models.DateTimeField(null=True),
        ),
    ]
