# Generated by Django 4.1.1 on 2022-10-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="rate",
            new_name="interest_rate",
        ),
    ]
