# Generated by Django 4.1.2 on 2022-10-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("OFFER", "Offer"),
                    ("LOAN", "Loan"),
                    ("AFTER_MATURITY", "After_maturity"),
                    ("INACTIVE_LOAN", "Inactive_loan"),
                    ("INACTIVE_OFFER", "Inactive_offer"),
                ],
                max_length=50,
            ),
        ),
    ]
